### PR TITLE
634 story about us page

### PR DESCRIPTION
**Pull request by notjoncruz**
This is not merge complete. I think they are existing components that I need to swap that already exist. 

Test it at http://localhost:3000/about-us

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

### CODE REVIEW

**Review by dm9965 — APPROVED** [review]
Just pull in updated development/ui-refresh branch and update the buttons on the About Us page to use the ALL Lab Buttons, and you should be good to go. Great job.

**Comment by heathermoses** [comment]
@notcruz Need to pull in `ui-refresh`, then I'll review!

**Comment by notjoncruz** [comment]
UI is pretty much done. We need to onboard a new service to fetch the new properties of Lab Credits and Favorite Lab (and a description of the team member)

https://github.com/all-rit/ALL/issues/673

**Review by heathermoses — APPROVED** [review]
This looks awesome I love it! I think you might need to pull in `ui-refresh` one more time, I noticed the navbar is missing here

**Pull request merged**
