### PR TITLE
624 story footer

### PR DESCRIPTION
**Pull request by mpb8984**
The new footer for the UI refresh. The UI implementation is pretty much complete. However, the actual functionality of sending emails using the contact us section hasnt been finished yet. All it does is log the entered values for now.  This is because of the requirements of a mail server, and we will be coming back to this in the future.

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

### CODE REVIEW

**Review by dm9965 — APPROVED** [review]
Looks great. We'll figure out the email situation once we have this pushed. Also, I have a fresh PNG of the ALL logo you can use for the branding. Great job!!

**Comment by heathermoses** [comment]
Looks like a few merge conflicts - fix these first then I'll approve!

**Review by heathermoses — APPROVED** [review]
LGTM

**Review by dm9965 — APPROVED** [review]
Looks great and redirects to what's needed! Approved!

**Pull request merged**
