### PR TITLE
Beginning work on dev partners

### LINKED ISSUE #625: Story: Development Partners
# Development Partners

As a **website visitor**, I want **to see key development partners**, so that **I can understand who is involved with the project**.

Image

Associated Epic: #619 

## Definition of Done

- [ ] Acceptance criteria defined
- [ ] Solution tasks specified
- [ ] Feature branch created
- [ ] ~~Unit tests written (on API code only for now)~~
- [ ] ~~Solution passes full suite of unit tests~~
- [ ] Design documents updated if needed
- [ ] Pull request created
- [ ] Code is reviewed
- [ ] Code is merged to `develop` branch
- [ ] ~~Tests pass on CI~~
- [ ] ~~Deployed to staging environment~~
- [ ] Acceptance criteria is met

## Acceptance Criteria

- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**
- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**
- [ ] Given **initial context**, when **event occurs**, then **some desired outcome**

## Solution Tasks

- [ ] [Task 1]
- [ ] [Task 2]
- [ ] [Task 3]

### PR DESCRIPTION
**Pull request by komeally**
Little bit of a rough draft, I haven't done front-end dev in a while so starting from scratch made it hard for me to conceptualize what HTML and Tailwind classes I needed to use. Haven't tested in browser yet, so this may all render as rubbish

- [ ] No discrepancies across browsers. Eg. chrome vs safari
- [ ] Pages pass W3C Validation for HTML (https://validator.w3.org)
- [ ] CSS (https://jigsaw.w3.org/css-validator/)
- [ ] Google sign-in is operational
- [ ] Accessibility functions
- [ ] Pages can scale without distorting page
- [ ] No dead links
- [ ] Navbar is consistent across the site
- [ ] Pages are screen-reader accessible
- [ ] Contrast meets standards for accessibility
- [ ] Pages are keyboard accessible
- [ ] Passes WAVE Evaluation Tool chrome extension

### CODE REVIEW

**Comment by heathermoses** [comment]
This is looking awesome, great job Kasim! I think you might be able to achieve the partial border by using something like `translate-x` and/or `translate-y` to get the partial effect. Keep up the great work and reach out if you need any help! :)

**Comment by komeally** [comment]
> This is looking awesome, great job Kasim! I think you might be able to achieve the partial border by using something like `translate-x` and/or `translate-y` to get the partial effect. Keep up the great work and reach out if you need any help! :)

Hmm, I am not getting translate-x or translate-y  to work. Dom and Jon mentioned using position absolute and relative, but I wasn't able to get much luck with that either

**Review by heathermoses — APPROVED** [review]
Awesome stuff Kasim!

**Review by dm9965 — APPROVED** [review]
LGTM

**Pull request merged**
